### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Xuddley** [cadon0/gif-to-the-beat#10]
Everytime i start the start.bat thing it just closes without asking me to enter the osu Songs folder. What do i have to do?

**Comment by cadon0** [comment]
Hi,

to get the error message could you please open PowerShell from the project folder, like so:

![image](https://user-images.githubusercontent.com/25311843/94378072-f011b280-0182-11eb-9bdc-f4ab2ff65e70.png)

And then enter the text `.\start.bat` and press enter (it might spam the error message - press `Ctrl+C` to stop it)

![image](https://user-images.githubusercontent.com/25311843/94378099-1f282400-0183-11eb-9ff9-1d814b0df5e6.png)

I actually got errors when I tried to run it myself just now.

There are a couple of things to try:
1) I've updated the full `.exe` file which you can [download here](https://github.com/cadon0/ProcessMemoryDataFinder/releases/download/v1.0.1/GifToTheBeatDataProvider-full.exe). Replace the old one and remove the `-full` from the name

or

2)  - Download the smaller `.exe` file [here](https://github.com/cadon0/ProcessMemoryDataFinder/releases/download/v1.0.1/GifToTheBeatDataProvider.exe) to replace the old one
    - Download and install the .NET Core runtime 3.1 [here](https://dotnet.microsoft.com/download/dotnet-core/current/runtime)

**Comment by cadon0** [comment]
There would also be

3)  - Replace the `.exe` with all of the files in [this .zip](https://github.com/cadon0/ProcessMemoryDataFinder/releases/download/v1.0.1/GifToTheBeatDataProvider.zip)
    - Download and install the .NET Core runtime 3.1 [here](https://dotnet.microsoft.com/download/dotnet-core/current/runtime)

**Comment by Xuddley** [comment]
It's working now.
Thank you very much for the help!
