### ISSUE TITLE
Gif not showing up

### ISSUE THREAD

**Issue by ScruffiX** [cadon0/gif-to-the-beat#11]
I set up everything up correctly (I think), start.bat is working and running but I can't see the image, neither on OBS nor in the Browser. Can anyone help?

**Comment by cadon0** [comment]
From the browser you could press F12 to open the developer tools and check if there are any errors on the "Console" or "Network" tabs (refresh the page after F12 to be sure)

If there aren't any errors then this information from the "Elements" tab might be the next most helpful thing to track down the problem
![image](https://user-images.githubusercontent.com/25311843/94994084-e5777300-05f1-11eb-8c2d-ea2dede2a8c2.png)

**Comment by ScruffiX** [comment]
I found the problem. I had to rename the imagine files, dk if that is said in the readme though (found it mentioned in the config). But it works now thanks for the reply
