### ISSUE TITLE
Gif not appearing on the website

### ISSUE THREAD

**Issue by koramint** [cadon0/gif-to-the-beat#12]
I'm using the catjam spritesheet you provided and everything should be in the right place
When the website starts it's just a white screen

**Comment by cadon0** [comment]
Hi,

Could you follow this comment please? https://github.com/cadon0/gif-to-the-beat/issues/11#issuecomment-703112828

And just to confirm - when it's running do you see the song information every few seconds?

**Comment by koramint** [comment]
I figured it out, turns out the catjam sprite sheet I downloaded wasn't the actual sprite sheet and it was some image that couldn't open. Not sure how I messed that one up. Thank you though, it works now.
