### ISSUE TITLE
I have to run the program as admin but it's not working like that.

### ISSUE THREAD

**Issue by inyafaze** [cadon0/gif-to-the-beat#13]
Somehow when I don't open osu! as admin it only refreshes maps all the time, it's broken and I cannot play, because of this i have to open osu! as admin and so i have to open streamlabs as admin, have to open streamcompanion as admin, or else these wouldn't work. 

Now i also have to open the start.bat as admin, which unfortunately isn't working. Is there anything I can do or will I never be able to use the program correctly? Because when i open it normally, not as admin the cat is jamming, but it is not jamming to the beat :/

When i open as admin, there are some red errors for a quick moment before the program just shuts itself down.

Thanks and greetings!

**Comment by cadon0** [comment]
Hello, 

You can open PowerShell or Command Prompt as admin to/in the project's folder (easiest way: check the `File` menu for a "Open Windows PowerShell here as administrator" option) and then type `.\start.bat` and hit enter. This should run it as before but if there are any errors the window will stay open so you can read them and/or take a picture to post here

**Comment by inyafaze** [comment]
Ok after some googling I did it and it works. Thanks!
