### ISSUE TITLE
Issue starting osu memory reader

### ISSUE THREAD

**Issue by L-udo** [cadon0/gif-to-the-beat#18]
Error Message:
Error:
  An assembly specified in the application dependencies manifest (GifToTheBeatDataProvider.deps.json) was not found:
    package: 'runtimepack.Microsoft.NETCore.App.Runtime.win-x86', version: '3.1.1'
    path: 'System.Diagnostics.Tools.dll'

Error running osu! memory reader:
Error: Command failed: C:\Users\username\OneDrive\Desktop\gif-to-the-beat+v1.0.01\GifToTheBeatDataProvider.exe 7270
Error:
  An assembly specified in the application dependencies manifest (GifToTheBeatDataProvider.deps.json) was not found:
    package: 'runtimepack.Microsoft.NETCore.App.Runtime.win-x86', version: '3.1.1'
    path: 'System.Diagnostics.Tools.dll'

Not sure whats goin on plz halp

**Comment by cadon0** [comment]
Hello,

could you please try replacing that executable (`C:\Users\username\OneDrive\Desktop\gif-to-the-beat+v1.0.01\GifToTheBeatDataProvider.exe`) with the latest `.exe` file [here](https://github.com/cadon0/ProcessMemoryDataFinder/releases) (get `GifToTheBeatDataProvider-full.exe
`and rename it to remove the `-full`)
