### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by nilkra** [cadon0/gif-to-the-beat#20]
Starting osu! memory reader...
Disconnected from feed of osu! data, reconnecting...
Disconnected from feed of osu! data, reconnecting...
Disconnected from feed of osu! data, reconnecting...
Disconnected from feed of osu! data, reconnecting...
Disconnected from feed of osu! data, reconnecting...
Disconnected from feed of osu! data, reconnecting...
Disconnected from feed of osu! data, reconnecting...
Disconnected from feed of osu! data, reconnecting...
Disconnected from feed of osu! data, reconnecting...
Disconnected from feed of osu! data, reconnecting...
Disconnected from feed of osu! data, reconnecting...
Disconnected from feed of osu! data, reconnecting...
Disconnected from feed of osu! data, reconnecting...
Disconnected from feed of osu! data, reconnecting...
Disconnected from feed of osu! data, reconnecting...
Disconnected from feed of osu! data, reconnecting...
The application to execute does not exist: 'C:\Users\<name>\AppData\Local\Temp\.net\GifToTheBeatDataProvider\xvqwwjrg.y50\GifToTheBeatDataProvider.dll'.

Error running osu! memory reader:
Error: Command failed: C:\Users\nilsk\Desktop\Stream\Osu\gif-to-the-beat+v1.0.0\GifToTheBeatDataProvider.exe 7270
The application to execute does not exist: 'C:\Users\<name>\AppData\Local\Temp\.net\GifToTheBeatDataProvider\xvqwwjrg.y50\GifToTheBeatDataProvider.dll'.

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  killed: false,
  code: 2147516570,
  signal: null,
  cmd: 'C:\\Users\\<name>\\Desktop\\Stream\\Osu\\gif-to-the-beat+v1.0.0\\GifToTheBeatDataProvider.exe 7270'
}

this is the Error message...it worked fine a few weeks ago but now its not working...

**Comment by cadon0** [comment]
Hi,

could you please try deleting that temporary folder? `C:\Users\<name>\AppData\Local\Temp.net\GifToTheBeatDataProvider\`

**Comment by nilkra** [comment]
Hey,

The folder cannot be found on my Computer.

**Comment by cadon0** [comment]
Ah I think there needs to be a `\` after `Temp`. If you just go to `C:\Users\<name>\AppData\Local\Temp` there should be a `.net` folder?

May need to enable Hidden items
![image](https://user-images.githubusercontent.com/25311843/104983440-a3275400-5a71-11eb-8431-513143e74b82.png)

**Comment by nilkra** [comment]
ah ok that worked thanks!

**Comment by cadon0** [comment]
👍
