### ISSUE TITLE
can't get it to work?

### ISSUE THREAD

**Issue by kettoph** [cadon0/gif-to-the-beat#21]
![image](https://user-images.githubusercontent.com/77633784/104942927-a55ab700-597a-11eb-8cbe-e64f78e154d1.png)
this is what happens when i run as admin
![image](https://user-images.githubusercontent.com/77633784/104943204-008ca980-597b-11eb-91c1-038127b7414f.png)
and this is without

either way, nothing shows up in obs. what's wrong?

**Comment by cadon0** [comment]
> ![image](https://user-images.githubusercontent.com/77633784/104943204-008ca980-597b-11eb-91c1-038127b7414f.png)
> and this is without

This one looks correct

> either way, nothing shows up in obs. what's wrong?

Do you see it if you open [http://localhost:727](http://localhost:727)?
The settings of the source in OBS should look something like this, and you may need to click the "Refresh cache of current page" button
![image](https://user-images.githubusercontent.com/25311843/104956903-efeb3a80-5a31-11eb-8c4b-1ead6bbc9891.png)

Edit: Should be able to ignore that custom CSS. It must be from when I was trying different things, it doesn't seem to do anything now
