### ISSUE TITLE
localhost wont work, i dont get any errors and the page is just white, ive triple checked the link

### ISSUE THREAD

**Issue by shotzz5** [cadon0/gif-to-the-beat#23]

**Comment by cadon0** [comment]
Hi,

can you confirm that when you start it you see something like this?
![image](https://user-images.githubusercontent.com/25311843/107641858-02772d80-6cd9-11eb-96c5-b33350740629.png)

Also when viewing localhost in your browser can you press f12 and refresh the page? There may be errors reported in the "Console" tab
![image](https://user-images.githubusercontent.com/25311843/107641973-263a7380-6cd9-11eb-99b8-e3b79ffc4485.png)

**Comment by shotzz5** [comment]
this happens when starting the program but after everything just runs fine i think

![34f6eb702bd6883c779cab50f9510213](https://user-images.githubusercontent.com/78761689/108294677-39908780-718e-11eb-895b-21b3cf70030b.png)

and this is my console after refreshing it
![3fd8b3f90f321c658bc218ac427e9fd8](https://user-images.githubusercontent.com/78761689/108294861-95f3a700-718e-11eb-91ac-248fe99b33f4.png)

sry for the late response
and sry for the shit screenshots

**Comment by cadon0** [comment]
It's possible that it can't find the image. Can you confirm that it's in the `app > images` folder?
(I thought there would be error messages if this happens, but I tried deleting the image and there aren't any 🙁)
![image](https://user-images.githubusercontent.com/25311843/108594070-9b463100-73dc-11eb-865e-7faff7f14064.png)

If the image is there then I'll also get you to click this in the Elements tab to make sure these settings are right
![image](https://user-images.githubusercontent.com/25311843/108593861-363e0b80-73db-11eb-89a1-bbb6e9187e7e.png)
