### ISSUE TITLE
Failed to load hostfxr.dll, can't get it working

### ISSUE THREAD

**Issue by 2BDia** [cadon0/gif-to-the-beat#24]
![image](https://user-images.githubusercontent.com/78406811/110664430-aca68000-81c7-11eb-87d0-6a12a99a9782.png)
I had to manually download hostfxr.dll and place it in the requested folder in AppData\Local\Temp\.net\GifToTheBeatDataProvider\txhwhbkd.y1g\, but now it's telling me it can't load it. I maybe need to install something else but I've tried installing basically every version and package of .NET 5.0 and nothing seems to work.

Thanks in advance :)

**Comment by cadon0** [comment]
Can I get you to try deleting the whole temp folder `AppData\Local\Temp.net\GifToTheBeatDataProvider`? Perhaps something went wrong with it. It will be created again when you start up the program and hopefully everything will be in order

Just for info - the "Data Provider" (`.exe` file in the folder you'll have) was created using .NET Core 3.1, so I'm not sure how it will behave with .NET 5. I could look to update it after work though. 🙂
I don't think it will help your issue but the `.exe` has [a newer version here](https://github.com/cadon0/ProcessMemoryDataFinder/releases) (if you downloaded the `.zip` file with everything in it already) so you could try replacing that

**Comment by 2BDia** [comment]
Thank you so much for your answer!

I got it to work by deleting the temp folder and by installing .NET Core 3.1 (just deleting it didn't work, I think .NET Core was the issue).
For info : I didn't have the sample image of catjam in the app\images folder and had to download it from the "How to use : Long version" part in your setup guide. I don't know if that's normal or not (and that's probably how some of the other issues happened from what I've read).

Again thanks a lot for your help and of course for your great plugin!
