### ISSUE TITLE
Upon opening "Disconnected from feed of osu! data, reconnecting..." 

### ISSUE THREAD

**Issue by Oweeeenxd** [cadon0/gif-to-the-beat#28]
Please bare with me, I am slow. 

It used to work for me without a problem and I dont know what I did or how I did it but it refuses to work even after reinstall.

running as admin provides this 
![catjam admin](https://user-images.githubusercontent.com/85284324/120621981-06fc5900-c424-11eb-858c-2ec8292fa626.png)

Regular startup
![catjam problem](https://user-images.githubusercontent.com/85284324/120621481-863d5d00-c423-11eb-94a8-a821cd9ad502.png)

the main text upon open(not admin)
![other catjam problem](https://user-images.githubusercontent.com/85284324/120622306-4d51b800-c424-11eb-9e02-6d60e0b0d2d7.png)

A gif does play from the localhost but stays at the constant default BPM

**Comment by Oweeeenxd** [comment]
Log from the crash on admin

![catjam log](https://user-images.githubusercontent.com/85284324/120623025-f5678100-c424-11eb-85e0-d61cd6511bae.png)

**Comment by cadon0** [comment]
I think this has happened to other people but I don't know why 🙁
Could you delete this folder please and try again?
![image](https://user-images.githubusercontent.com/25311843/120629054-838d4700-c4b9-11eb-8ba7-cb121360d246.png)

**Comment by Oweeeenxd** [comment]
i have no clue how that made it work but it works again, tysm!
