### ISSUE TITLE
new image link?

### ISSUE THREAD

**Issue by fourennnn** [cadon0/gif-to-the-beat#29]
i got everything to work, except im trying to get a new gif instead of catjam. the instructions say to upload the spritesheet and put the link, which I did, but catjam still shows up. i went into server > config, and edited the notepad, added my new gif, changed the name and location of the file to match mine, but it still shows up at catjam. how do I change the gif?

**Comment by cadon0** [comment]
Hi, I'm not sure what the issue could be. If you posted the text or pictures it could help, for example the config file and the link you are using.

Make sure the `gifName` is at the end of the link. e.g. if the `gifName` was "MyNewGif" then http://localhost:727/MyNewGif (must be same capital letters)
By default it will take the first section from the `gifConfigurations` in the config file, so you could delete the others or move your new one above the catjam one instead

If you are looking through OBS then clearing the cache might help as well

![image](https://user-images.githubusercontent.com/25311843/127991793-fcffb975-c224-4dd4-9c70-1125a2c32530.png)

If you are looking at it with chrome then to clear the cache you can press f12, then right click the refresh button for this menu
![image](https://user-images.githubusercontent.com/25311843/127992575-6f051e0b-742c-4e2a-af36-2793267b80b4.png)

**Comment by fourennnn** [comment]
> Hi, I'm not sure what the issue could be. If you posted the text or pictures it could help, for example the config file and the link you are using.
> 
> Make sure the `gifName` is at the end of the link. e.g. if the `gifName` was "MyNewGif" then http://localhost:727/MyNewGif (must be same capital letters)
> By default it will take the first section from the `gifConfigurations` in the config file, so you could delete the others or move your new one above the catjam one instead
> 
> If you are looking through OBS then clearing the cache might help as well
> 
> ![image](https://user-images.githubusercontent.com/25311843/127991793-fcffb975-c224-4dd4-9c70-1125a2c32530.png)
> 
> If you are looking at it with chrome then to clear the cache you can press f12, then right click the refresh button for this menu
> ![image](https://user-images.githubusercontent.com/25311843/127992575-6f051e0b-742c-4e2a-af36-2793267b80b4.png)

refreshing the cache in obs worked! thank you for the quick reply and the helpful advice, I enjoy this program very much and look forward to using it :D

**Comment by cadon0** [comment]
Thanks for the interest 🙂 I'll add a note for this to the instructions
