### ISSUE TITLE
not working anymore

### ISSUE THREAD

**Issue by fourennnn** [cadon0/gif-to-the-beat#30]
hey, I've been using the software and it's been working and looking great, but now it's not working. everytime I run the program, it says somethings outdated and to run "npx browserslist@latest --update-db", and repeatedly shows a block of text (picture below) . I input the command into shell (opened as administrator), but it doesn't fix anything, and says "npx: installed 6 in 2.963s
Cannot find package.json. Is this the right directory to run `npx browserslist --update-db` in?"
![problem](https://user-images.githubusercontent.com/88369252/129115083-79b300ee-095c-4a63-babd-dcb2c2ed6fbc.png)

**Comment by cadon0** [comment]
Hi,

don't worry about the `npx browserslist` thing, you can ignore it

![image](https://user-images.githubusercontent.com/25311843/129130646-a7a966e8-e6fa-43dd-bc1e-14c75a2c3621.png)
This part is a problem though. Could you please download the latest `.exe` [from this list](https://github.com/cadon0/ProcessMemoryDataFinder/releases), specifically [this one](https://github.com/cadon0/ProcessMemoryDataFinder/releases/download/v1.0.1/GifToTheBeatDataProvider-full.exe) (remove the `-full` from the name), and replace the `.exe` file in your `gif-to-the-beat` folder with it

**Comment by fourennnn** [comment]
this worked! thank you for the continuous help! if i have any more problems i will be sure to forward them to you, thank you very much!
