### ISSUE TITLE
not working again

### ISSUE THREAD

**Issue by fourennnn** [cadon0/gif-to-the-beat#31]
Hey, (I'm not sure why i keep having problems, so sorry about that lol) there is an issue whenever I open the "start" in the folder. the image below constantly repeats, is there a fix to this? thank you!
![image](https://user-images.githubusercontent.com/88369252/131393451-87d9a6fe-3a7f-4966-9cef-6df49f5dc098.png)

**Comment by cadon0** [comment]
No problem. Could you delete this folder in `C:\Users\<username>\AppData\Local\Temp\.net`
![image](https://user-images.githubusercontent.com/25311843/131464337-fa6c7641-a2c3-480b-abd8-10d517c3df45.png)

The `.exe` seems to "install" itself there, and deleting the folder makes it reset

**Comment by fourennnn** [comment]
this worked! looking at the page now, I can see that there is already a common issue fix there, so sorry about this post! lol
