### ISSUE TITLE
Can't add custom gif

### ISSUE THREAD

**Issue by Onii-chanexe** [cadon0/gif-to-the-beat#32]
So, for a while now, i've been trying to add a custom gif, but I just can't get it to work 
![Cerberus](https://user-images.githubusercontent.com/83355661/132395556-69f7a533-e988-4602-83bf-29acaf852d1c.gif)
î thats the gif btw

**Comment by cadon0** [comment]
Hi!

I imagine you've seen the [custom gif instructions](https://github.com/cadon0/gif-to-the-beat#how-do-i-add-a-different-gif)? Where did you get to?

If you want to upload anything you have so far I could check out the part you're stuck on

**Comment by Onii-chanexe** [comment]
Hello

Yes, i've seen the instructoins and they helped me to get the gif displayed at localhost727 but the gif froze instantly. I really dont know why
That below is the code I have in config.js
   // A name - used to match with URLs e.g. `http://localhost:727/horny`
    gifName: "horny",
    // Dimensions of the gif
    width: 112,
    height: 112,
    spritesheetWidth: 1200,
    // "BPM" of the Original gif
    originalBpm: 142,
    // Length of the original gif
    seconds: 0.84,
    // Milliseconds until the gif hits the first "beat".
    // Increase to start earlier, decrease to start later
    gifOffset: 15,
    // The location of the sprite sheet for the gif, either a URL
    // or the name of a file in the images folder with "./" in front
    spritesheetLocation: "./horny.png",

**Comment by Onii-chanexe** [comment]
Small update: Figured it out! Just had wrong dimensions still thanks!

**Comment by cadon0** [comment]
Great! Thanks for the interest 🙂
