### ISSUE TITLE
cant even get an error code to show

### ISSUE THREAD

**Issue by Whiff123** [cadon0/gif-to-the-beat#33]
whenever i try to run start.bat or run it through powershell, im getting no error codes but the command prompt closes instantly. 
i tried the solutions in #10 but had no luck, this is likely something simple that i just dont know how to go about fixing it

**Comment by cadon0** [comment]
Hi, could you upload a screenshot of powershell after you try to run it please?

**Comment by Whiff123** [comment]
https://user-images.githubusercontent.com/90311015/138997913-1a623e70-9911-4710-af53-ffba1d08d10d.mp4

I've tried reinstalling node.js at least 5 times now, as well with java, I was able to get the program working on a pc at my school in seconds, so I think it may be an interfering program. Though I'm not really sure how I'm supposed to locate the issue here

**Comment by cadon0** [comment]
Oh I see. Perhaps something on your pc handles `.bat` files differently? I think usually I don't see it opening in a new window.

Anyway the file itself doesn't do much (see [here](https://github.com/cadon0/gif-to-the-beat/blob/master/start.bat)) - it's just meant to be convenient. You can run the program without it.
From the powershell window you can enter `npm ci` which downloads missing files, then when it's finished downloading `npm start` will start the program
