### ISSUE TITLE
german letter ü in username

### ISSUE THREAD

**Issue by ssachiii** [cadon0/gif-to-the-beat#34]
Hi, 

I ran into a problem with my username while entering the file path into node.
My username contains the german letter ü and i dont know how to enter that into node.
I tried ue because thats how its usually abreviated but it couldnt find the files then.

**Comment by cadon0** [comment]
Hi! Good question. I'm not sure how to enter that either - I created a user on my computer with this `ü` character and trying to copy+paste didn't work.

After entering the path normally the program will just store it in a text file. You can create this file yourself and it will stop asking for the path. Create a file called `song-directory.txt` (in the same folder as the `start.bat` file) and paste the path into it. Example file: 
[song-directory.txt](https://github.com/cadon0/gif-to-the-beat/files/7207304/song-directory.txt)
