### ISSUE TITLE
Easier way to find temp.net?

### ISSUE THREAD

**Issue by fourennnn** [cadon0/gif-to-the-beat#35]
I keep having the same "temp.net" problem, and I fixed it once, but it came back. is there a quick way to find the file? I cant seem o find it in AppData, so I am opening file explorer and searching "gif=to-the-beat", and it takes about 10 whole minutes for the results to even appear, which is a huge pain. so I was wondering if there was an easier way to find and delete the file?

**Comment by cadon0** [comment]
should always be here `C:\Users\<username>\AppData\Local\Temp\.net`

**Comment by cadon0** [comment]
the executable has been updated to be compatible with the latest version of osu! ([download here](https://github.com/cadon0/ProcessMemoryDataFinder/releases/download/v1.0.2/GifToTheBeatDataProvider.exe)).

it includes some other updates (a more recent version of .NET, which is used to create that exe), so there's a chance this kind of error will stop happening...
