### ISSUE TITLE
weird error?

### ISSUE THREAD

**Issue by WageShoe** [cadon0/gif-to-the-beat#36]
get this repeatedly in the cmd prompt window

'C:\Users\weiji\AppData\Local\osu!\Songs\123593 Rostik - Liquid (Paul Rosenthal Remix)\ㆨο丌ο'
(node:5600) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 97)
(node:5600) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open

**Comment by cadon0** [comment]
Thanks for reporting this. I think it stopped working because of an update to osu! (I can see [StreamCompanion](https://github.com/Piotrekol/StreamCompanion) was updated to fix this). It will probably take me a bit of time to get an update out. I'll reply here when it's ready

**Comment by WageShoe** [comment]
thank you for your hardwork

**Comment by cadon0** [comment]
Hi!

Could you please download the latest executable here to replace the old one and try it out? 🙂 
https://github.com/cadon0/ProcessMemoryDataFinder/releases/tag/v1.0.2 ([direct download link](https://github.com/cadon0/ProcessMemoryDataFinder/releases/download/v1.0.2/GifToTheBeatDataProvider.exe))

**Comment by WageShoe** [comment]
thank you it works again

**Comment by cadon0** [comment]
Great. Thanks!
