### ISSUE TITLE
Start not working

### ISSUE THREAD

**Issue by Yeticat** [cadon0/gif-to-the-beat#37]
After opening Start.bat it crashes instantly. This is the error I get
![unknown](https://user-images.githubusercontent.com/100801766/156441506-f023834d-407b-4da2-9c51-2936aa203b64.png)

I've looked through other issues and nothing seems to help.

**Comment by cadon0** [comment]
Hi,

I tried Node.js version 17 and it looks like something is incompatible. If you could please install a version of Node at 16 or lower instead it should be ok. I would recommend the [latest LTS version, right now that's 16.14.0](https://nodejs.org/dist/v16.14.0/node-v16.14.0-x64.msi).

I will update the requirements as well.

Let me know if you need Node 17 for other reasons and I can try and get an update out

**Comment by cadon0** [comment]
Actually it's straight forward to resolve, you can run this command from the `gif-to-the-beat` folder instead if you like `npm i -D webpack@latest webpack-cli@latest`, from command prompt or powershell

Simple way to open powershell for the folder:
![image](https://user-images.githubusercontent.com/25311843/156467929-0ac9041a-da55-47d6-8350-075221108e06.png)
