### ISSUE TITLE
Not detecting Songs folder

### ISSUE THREAD

**Issue by Ch0p** [cadon0/gif-to-the-beat#38]
Hey,

since a few days I get this when I start the program. (See image)
![Bild_2022-04-23_164641003](https://user-images.githubusercontent.com/58478474/164910988-51c85c20-0b4d-4be5-b85d-f553a76922bd.png)

Any solution?

**Comment by cadon0** [comment]
Not sure sorry. Sometimes it needs updating after osu! updates, but I've got limited internet access right now so it might be a few days before I can check

**Comment by cadon0** [comment]
If you're comfortable with running projects yourself, you can try updating [this package to version 0.8.9](https://github.com/cadon0/ProcessMemoryDataFinder/blob/master/GifToTheBeatDataProvider/GifToTheBeatDataProvider.csproj#L19)

**Comment by cadon0** [comment]
Hi, I've updated it. Please download the new [GifToTheBeatProvider.exe](https://github.com/cadon0/ProcessMemoryDataFinder/releases) and replace the old one ([direct download link](https://github.com/cadon0/ProcessMemoryDataFinder/releases/download/v1.0.3/GifToTheBeatDataProvider.exe))

Thanks for the report!
