### ISSUE TITLE
it doesnt work when osu game is running

### ISSUE THREAD

**Issue by Tanniieee** [cadon0/gif-to-the-beat#40]
The cat gif works before i launch osu. As soon as I launch the game, the start.bat window just closes and if I go to refresh the localhost page, it'll say the site can't be reached. I assumed it is because start.bat window isn't running anymore. I can have catjam gif work in obs as long as I don't refresh localhost page while having osu running but it will just not sync with the beatmap at all, the gif is running at a stable pace. Also one thing I manage to catch while launching start.bat is that it says:

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

which I have no clue how to do this. the gif used to work just fine and changes speed pretty much immediately as soon as I change the beatmap in game but now it just doesn't.
Thanks.

**Comment by cadon0** [comment]
Thanks for the report! Fixed today, see #38 (same issue)

Solution:
> Please download the new [GifToTheBeatProvider.exe](https://github.com/cadon0/ProcessMemoryDataFinder/releases) and replace the old one ([direct download link](https://github.com/cadon0/ProcessMemoryDataFinder/releases/download/v1.0.3/GifToTheBeatDataProvider.exe))
