### ISSUE TITLE
Program no longer works?

### ISSUE THREAD

**Issue by TheOttoZone** [cadon0/gif-to-the-beat#44]
Hi! I don't really know how to make a proper GitHub issue, but when trying to use the program, these just get spammed in the console it opens up:
`(node:22036) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)`
`(node:23824) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'C:\Users\MYUSERNAME\Appdata\Local\osu!\Songs\143397 Natsume Chiaki - Hanairo Biyori\[bold:0,size:20]なつめ千秋
花色日和'`
The gif never gets synced up to the music. Is this a problem on my end or does this need fixing on the developer end?

**Comment by cadon0** [comment]
Thanks for the report! Sometimes that happens when the game updates. If you could [grab the new `.exe` here](https://github.com/cadon0/ProcessMemoryDataFinder/releases/tag/v1.0.4) and replace it in the folder

**Comment by TheOttoZone** [comment]
Thanks! Works perfectly now!
